language: node_js
node_js:
  - "11"

install:
  - npm install

before_script:
  - npm install --global ganache-cli
  - npm install --global truffle

script:
  - ganache-cli &
  - sleep 5
  - truffle test
