// List of errors and respective messages issued by Bileto.

const biletoErrors = {
  BILETO001: "ticket store must be open",
  BILETO002: "invalid event ID",
  BILETO003: "invalid purchase ID",
  BILETO004: "must be triggered by event organizer",
  BILETO005: "must be triggered by event organizer or store owner",
  BILETO006: "ticket purchase have to be completed",
  BILETO007: "store name must not be empty",
  BILETO008: "only funds transfer (i.e. no data) accepted on fallback",
  BILETO009: "ticket store must be created or suspended",
  BILETO010: "ticket store cannot be closed",
  BILETO011: "ticket store refundable balance must be zero",
  BILETO012: "organizer address must refer to an account (i.e. not a contract)",
  BILETO013: "ticket event external ID must not be empty",
  BILETO014: "ticket event name must not be empty",
  BILETO015: "store incentive must be between 0 and 100%",
  BILETO016: "number of tickets available for sale cannot be zero",
  BILETO017: "event status must be created or with ticket sales suspended",
  BILETO018: "event ticket sales must have started",
  BILETO019: "event ticket sales must have started or be suspended",
  BILETO020: "event ticket sales must have finished",
  BILETO021: "event must have been completed",
  BILETO022: "event status must be created or not completed",
  BILETO023: "event ticket sales have to had started",
  BILETO024: "customer address must refer to an account (i.e. not a contract)",
  BILETO025: "quantity of tickets must be greater than zero",
  BILETO026: "not enough tickets left. please change quantity",
  BILETO027: "purchase external ID must not be empty",
  BILETO028: "purchase date must be provided (not zero)",
  BILETO029: "customer ID cannot be empty",
  BILETO030: "customer funds must be equal to purchase total",
  BILETO031: "event status must allow cancellation",
  BILETO032: "purchase cancellation must be initiated by customer",
  BILETO033: "hash of customer ID must match with stored one",
  BILETO034: "hash of purchase external ID must match with stored one",
  BILETO035: "ticket purchase have to be cancelled",
  BILETO036: "event ticket sales should be started/suspended/finished",
  BILETO037: "check-in request must be initiated by customer",
  BILETO038: "must be triggered by customer, event organizer or store owner",
  BILETO039: "not allowed to retrieve information (not owner or organizer)",
  BILETO040: "organizer has not created events yet",
  BILETO041: "invalid index (organizerEvents)",
  BILETO042: "not allowed to retrieve information (not owner or customer)",
  BILETO043: "customer has not purchased tickets yet",
  BILETO044: "invalid index (customerPurchases)",
  BILETO045: "invalid index (organizers)",
  BILETO046: "invalid index (customers)"
};
